### ISSUE TITLE
Unable to train

### ISSUE THREAD

**Issue by starofgit** [ultralytics/xview-yolov3#18] opened 2019-07-19 09:28 UTC
I am getting the following error while training:
Traceback (most recent call last):
  File "train.py", line 209, in <module>
    main(opt)
  File "train.py", line 131, in main
    weight=class_weights, epoch=epoch).to(device)
  File "/home/xxxxx/anaconda3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xxxxx//xview/xview-yolov3-master/models.py", line 234, in forward
    x, losses = module[0](x, targets, requestPrecision, weight, epoch)
ValueError: too many values to unpack (expected 2)

I have checked that above call is returning 14 values.
Is it because of torch version mismatch?

**Comment by glenn-jocher** [comment] 2019-07-19 12:09
Hello, thank you for your interest in our work! This is an automated response. Please note that most technical problems are due to:

- **Your changes to the default repository**. If your issue is not reproducible in a fresh `git clone` version of this repository we can not debug it. Before going further run this code and ensure your issue persists:
```bash
sudo rm -rf yolov3  # remove exising repo
git clone https://github.com/ultralytics/yolov3 && cd yolov3 # git clone latest
python3 detect.py  # verify detection
python3 train.py  # verify training (a few batches only)
# CODE TO REPRODUCE YOUR ISSUE HERE
```
- **Your custom data.** If your issue is not reproducible with COCO data we can not debug it. Visit our [Custom Training Tutorial](https://github.com/ultralytics/yolov3/wiki/https://github.com/ultralytics/yolov3/wiki/Train-Custom-Data) for exact details on how to format your custom data. Examine `train_batch0.jpg` and `test_batch0.jpg` for a sanity check of training and testing data.
- **Your environment.** If your issue is not reproducible in a [GCP Quickstart Guide](https://github.com/ultralytics/yolov3/wiki/GCP-Quickstart) VM we can not debug it. Ensure you meet the requirements specified in the README: Unix, MacOS, or Windows with Python >= 3.7, Pytorch >= 1.1, etc. You can also use our [Google Colab Notebook](https://colab.research.google.com/drive/1G8T-VFxQkjDe4idzN8F-hbIBqkkkQnxw) to test your code in working environment.

If none of these apply to you, we suggest you close this issue and raise a new one using the **Bug Report template**, providing screenshots and **minimum viable code to reproduce your issue**. Thank you!

**Closed** 2019-07-24 05:26 UTC
